name: Docker build and deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: morisab/tamiyochi
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Copy Nginx configuration and Docker-Compose file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: azureuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./nginx.conf, ./docker-compose.yml"
          target: "~/tamiyochi/"
          overwrite: true

      - name: Execute remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: azureuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/tamiyochi
            sudo docker pull morisab/tamiyochi:latest
            sudo docker compose down
            sudo docker compose up -d
